# Generated by Django 3.2.3 on 2021-09-20 08:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import raymedasset.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('desktop', 'Стационарный компьютер'), ('laptop', 'Ноутбук'), ('monoblock', 'Моноблок'), ('monitor', 'Монитор'), ('externaldisk', 'Внешний жесткий диск'), ('flashdrive', 'Флешка'), ('periphery', 'Мышь\\клавиатура'), ('case', 'Сумка'), ('other', 'Другое')], max_length=15, verbose_name='Тип устройства')),
                ('model', models.CharField(max_length=50, verbose_name='Модель устройства')),
                ('descriptions', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('serial_number', models.CharField(max_length=25, verbose_name='Серийный номер')),
                ('number_account', models.CharField(blank=True, max_length=15, verbose_name='Номер счета')),
                ('provider', models.CharField(blank=True, max_length=15, null=True, verbose_name='Поставщик')),
                ('cost', models.IntegerField(blank=True, default=0, null=True, verbose_name='Стоимость(руб)')),
                ('closed_document', models.FileField(blank=True, upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'docx'])], verbose_name='Закрывающий документ')),
            ],
            options={
                'verbose_name': 'Устройство',
                'verbose_name_plural': 'Устройства',
            },
        ),
        migrations.CreateModel(
            name='Subdevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ssd', 'SSD'), ('ram', 'Оперативная память')], max_length=20, verbose_name='Тип устройства')),
                ('model', models.CharField(max_length=50, verbose_name='Модель устройства')),
                ('descriptions', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('serial_number', models.CharField(max_length=25, verbose_name='Серийный номер')),
                ('number_account', models.CharField(blank=True, max_length=15, verbose_name='Номер счета')),
                ('provider', models.CharField(blank=True, max_length=15, null=True, verbose_name='Поставщик')),
                ('cost', models.IntegerField(blank=True, default=0, null=True, verbose_name='Стоимость(руб)')),
                ('closed_document', models.FileField(blank=True, upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'docx'])], verbose_name='Закрывающий документ')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raymedasset.device')),
            ],
            options={
                'verbose_name': 'Комплектующие',
                'verbose_name_plural': 'Комплектующие',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, validators=[raymedasset.models.validators_FIO], verbose_name='Имя')),
                ('last_name', models.CharField(max_length=15, validators=[raymedasset.models.validators_FIO], verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=15, validators=[raymedasset.models.validators_FIO], verbose_name='Отчество')),
                ('department', models.CharField(blank=True, choices=[('manage', 'Управление'), ('sekretary', 'Секретариат'), ('buhgaltery', 'Бухгалтерия'), ('ekonom', ' Эконом.отдел'), ('legal', 'Правовой'), ('registration', 'Регистрации и сертификации'), ('commercial', 'Коммерческий'), ('hr', 'Управление персоналом'), ('tender', 'Тендерный'), ('warehouse', 'Склад'), ('transport', 'Транспортный'), ('logistics', 'Логистика'), ('purchases', 'Закупки'), ('security', 'Безопасность'), ('ahch', 'АХЧ'), ('it', 'IT'), ('production', 'Производство')], max_length=20, verbose_name='Отдел')),
                ('amount_laptop', models.IntegerField(default=0)),
                ('amount_desktop', models.IntegerField(default=0)),
                ('amount_monitor', models.IntegerField(default=0)),
                ('amount_monoblock', models.IntegerField(default=0)),
                ('amount_ex_disk', models.IntegerField(default=0)),
                ('amount_flash', models.IntegerField(default=0)),
                ('date_add_person', models.DateTimeField(verbose_name='Дата добавление сотрудника в БД')),
                ('image', models.ImageField(blank=True, upload_to='images/avatar/', verbose_name='Фото')),
                ('serial_pasport', models.CharField(default='0000', max_length=4, validators=[raymedasset.models.validators_serial], verbose_name='Серия паспорта')),
                ('number_pasport', models.CharField(default='000000', max_length=6, validators=[raymedasset.models.validators_number], verbose_name='Номер паспорта')),
                ('internal_number_phone', models.CharField(blank=True, max_length=3, validators=[raymedasset.models.validators_number_phone], verbose_name='Внутренний номер телефона')),
                ('number_phone', models.CharField(blank=True, max_length=11, validators=[raymedasset.models.validators_number_phone], verbose_name='Номер телефона')),
                ('date_birthday', models.DateField(verbose_name='Дата рождения')),
                ('user', models.ForeignKey(blank=True, default='0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='raymedasset.person'),
        ),
    ]
