# Generated by Django 3.2.4 on 2021-10-06 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raymedasset', '0003_auto_20210920_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='amount_desktop',
        ),
        migrations.RemoveField(
            model_name='person',
            name='amount_ex_disk',
        ),
        migrations.RemoveField(
            model_name='person',
            name='amount_flash',
        ),
        migrations.RemoveField(
            model_name='person',
            name='amount_laptop',
        ),
        migrations.RemoveField(
            model_name='person',
            name='amount_monitor',
        ),
        migrations.RemoveField(
            model_name='person',
            name='amount_monoblock',
        ),
    ]
