# Generated by Django 3.2.3 on 2021-11-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raymedasset', '0004_auto_20211006_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=30, verbose_name='Почта'),
        ),
        migrations.AddField(
            model_name='person',
            name='email_login',
            field=models.CharField(blank=True, max_length=15, verbose_name='Логин для входа в почту'),
        ),
        migrations.AddField(
            model_name='person',
            name='email_password',
            field=models.CharField(blank=True, max_length=15, verbose_name='Пароль для входа в почту'),
        ),
    ]
