# Generated by Django 3.2.3 on 2021-11-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raymedasset', '0005_auto_20211116_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='email_login',
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=50, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email_password',
            field=models.CharField(blank=True, max_length=50, verbose_name='Пароль для входа в почту'),
        ),
    ]
