# Generated by Django 3.2.4 on 2022-03-16 11:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raymedasset', '0006_auto_20211116_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='organization',
            field=models.CharField(blank=True, default='Раймед ТГ ПВТ', max_length=20, null=True, verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='subdevice',
            name='organization',
            field=models.CharField(blank=True, default='Раймед ТГ ПВТ', max_length=20, null=True, verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='device',
            name='number_account',
            field=models.CharField(blank=True, max_length=50, verbose_name='Номер счета'),
        ),
        migrations.AlterField(
            model_name='subdevice',
            name='number_account',
            field=models.CharField(blank=True, max_length=50, verbose_name='Номер счета'),
        ),
        migrations.CreateModel(
            name='HistoryMoveDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_get_device', models.DateField(default=datetime.datetime(2022, 3, 16, 14, 46, 17, 942909), verbose_name='Дата получения устройства')),
                ('date_receive_device', models.DateField(blank=True, null=True, verbose_name='Дата конца владения устройством')),
                ('current_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current', to='raymedasset.person')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='raymedasset.device')),
                ('old_person', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='raymedasset.person')),
            ],
            options={
                'verbose_name': 'История перемещения',
                'verbose_name_plural': 'Истории перемещения',
            },
        ),
    ]
