# Generated by Django 3.2.3 on 2021-09-21 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='error',
            options={'verbose_name': 'Проблема', 'verbose_name_plural': 'Проблемы'},
        ),
        migrations.RenameField(
            model_name='error',
            old_name='post_message',
            new_name='time_post_message',
        ),
    ]
