# Generated by Django 3.2.3 on 2021-09-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0005_alter_error_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='status',
            field=models.CharField(choices=[('wait', 'Ожидание'), ('in_work', 'В работе'), ('ready', 'Готово')], default='Ожидание', max_length=30, verbose_name='Статус обращения'),
        ),
    ]
