# Generated by Django 3.2.3 on 2021-09-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0006_alter_error_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='image_error',
            field=models.ImageField(blank=True, upload_to='images/error/', verbose_name='Скриншот ошибки'),
        ),
        migrations.AlterField(
            model_name='error',
            name='status',
            field=models.CharField(choices=[('wait', 'Ожидание'), ('in_work', 'В работе'), ('ready', 'Готово')], default='wait', max_length=30, verbose_name='Статус обращения'),
        ),
    ]
