# Generated by Django 3.2.3 on 2021-09-27 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raymedasset', '0003_auto_20210920_1109'),
        ('helpdesk', '0007_auto_20210927_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='raymedasset.device'),
        ),
    ]
